services:
  backend:
    image: tauseef0007/skill-tracker:latest
    environment:
      - DB_HOST=trolley.proxy.rlwy.net
      - DB_PORT=47081
      - DB_USER=root
      - DB_PASSWORD=NhdKFQPznznQEcJOqAYSXLFTLQToAxYx
      - DB_NAME=railway
    expose:
      - "8080"

  frontend:
    image: tauseef0007/skill-tracker-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend