apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  DB_HOST: trolley.proxy.rlwy.net
  DB_PORT: "47081"
  DB_USER: root
  DB_PASSWORD: NhdKFQPznznQEcJOqAYSXLFTLQToAxYx
  DB_NAME: railway